### ISSUE TITLE
JSON log formatting.

### ISSUE THREAD

**Issue by petersilva** [MetPX/sarracenia#716]
user request:

```
Is there an easy want to customize the logging config in sr3? We do
most of our logging in JSON (with the python-json-logger package), so
that it can be easily ingested to our elasticsearch/logstash/kibana
cluster. Usually with a logging config such as:

handlers:
  file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: json
    backupCount: 10
    maxBytes: 10000000
    filename: 'crmprtd_log.txt'
```
